#!/usr/bin/env sh
HASHED=`head -100 /dev/urandom | md5sum | tr -d [:blank:]`
FILENAME=/tmp/clj-script-$HASHED.clj

tail -n +2 $@ | sed '/^\s*$/d' | sed '/^#!/d' > $FILENAME

java -cp /opt/clojure/clojure-1.6.0.jar clojure.main $FILENAME
