---
- hosts: web
  remote_user: root

  tasks:
    - name: install go
      apt: name=golang state=latest

    - name: install dictionary
      apt: name=wamerican state=latest

    - name: create gopath
      command: mkdir /gopath
        creates=/gopath

    - name: download present
      command: env GOPATH=/gopath go get -u code.google.com/p/go.tools/cmd/present

    - name: install present
      command: env GOPATH=/gopath go install code.google.com/p/go.tools/cmd/present

    - name: download forego
      command: env GOPATH=/gopath go get -u github.com/ddollar/forego

    - name: install forego
      command: env GOPATH=/gopath go install github.com/ddollar/forego
