---
- hosts: web
  remote_user: root

  tasks:
    - name: install base packages
      apt: name={{item}} state=latest update_cache=yes cache_valid_time=3600
      with_items:
        - git
        - make
        - mercurial
        - unzip
        - wget
        - software-properties-common
        - python-software-properties
