---
- hosts: web
  remote_user: root

  tasks:
    - name: download erlang
      command: wget http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
        creates=erlang-solutions_1.0_all.deb

    - name: install erlang package list
      command: dpkg -i erlang-solutions_1.0_all.deb

    - name: install erlang and elixir
      apt: name={{item}} state=latest update_cache=yes
      with_items:
        - esl-erlang
        - elixir

    - name: install elixir runner
      template: src=../templates/elixir-run dest=/usr/local/bin mode=775
