---
- hosts: web
  remote_user: root

  tasks:
    - name: install mono and fsharp
      apt: name={{item}} state=latest update_cache=yes
      with_items:
        - mono-complete
        - fsharp

    - name: install fsharp runner
      template: src=../templates/fsharp-run dest=/usr/local/bin mode=775
